# coding: utf-8
# 
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization

import math
from typing import Optional, Tuple, Union, List, Callable, Dict, Any
from torch.nn import LayerNorm
import pdb

class DRAGON(GeneralRecommender):
    def __init__(self, config, dataset):
        super(DRAGON, self).__init__(config, dataset)
        # self.gate = nn.Sequential(
        #     nn.Linear(128,64),
        #     nn.Sigmoid())
        num_user = self.n_users
        num_item = self.n_items
        batch_size = config['train_batch_size']  # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.knn_k = config['knn_k']
        self.mm_image_weight = config['mm_image_weight']
        self.v_weight = config['v_weight']
        self.t_weight = 1 - self.v_weight
        has_id = True
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = config['aggr_mode']
        self.user_aggr_mode = 'softmax'
        self.num_layer = 1
        self.cold_start = 0
        self.dataset = dataset
        self.mmd = MMDLoss()
        # self.construction = 'weighted_max'
        # self.construction = 'weighted_sum'
        self.construction = 'cat'
        self.reg_weight = config['reg_weight']
        self.drop_rate = 0.1
        self.v_rep = None
        self.t_rep = None
        self.v_preference = None
        self.t_preference = None
        self.dim_latent = 64
        self.dim_feat = 128

        self.mm_adj = None

        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        self.user_graph_dict = np.load(os.path.join(dataset_path, config['user_graph_dict_file']),
                                       allow_pickle=True).item()

        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        if self.v_feat is not None:
            self.image_embedding = nn.Embedding.from_pretrained(self.v_feat, freeze=False)
            # self.image_trs = nn.Linear(self.v_feat.shape[1], self.feat_embed_dim)
        if self.t_feat is not None:
            self.text_embedding = nn.Embedding.from_pretrained(self.t_feat, freeze=False)
            # self.text_trs = nn.Linear(self.t_feat.shape[1], self.feat_embed_dim)

        if os.path.exists(mm_adj_file):
            self.mm_adj = torch.load(mm_adj_file)
        else:
            if self.v_feat is not None:
                indices, image_adj = self.get_knn_adj_mat(self.image_embedding.weight.detach())
                self.mm_adj = image_adj
            if self.t_feat is not None:
                indices, text_adj = self.get_knn_adj_mat(self.text_embedding.weight.detach())
                self.mm_adj = text_adj

            if self.v_feat is not None and self.t_feat is not None:
                self.mm_adj = self.mm_image_weight * image_adj + (1.0 - self.mm_image_weight) * text_adj
                del text_adj
                del image_adj
            torch.save(self.mm_adj, mm_adj_file)

        # packing interaction in training into edge_index
        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)
        edge_index = self.pack_edge_index(train_interactions)
        # edge_index (118551, 2)
        # print("edge_index", edge_index.shape)
        self.edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous().to(self.device)
        # self.edge_index torch.Size([2, 118551])
        # print("self.edge_index", self.edge_index.shape)

        self.edge_index = torch.cat((self.edge_index, self.edge_index[[1, 0]]), dim=1)
        #  torch.Size([2, 237102])
        # print("self.edge_index.cat", self.edge_index.shape)

        # pdb.set_trace()
        self.weight_u = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_user, 2, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_u.data = F.softmax(self.weight_u, dim=1)

        self.weight_i = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_item, 2, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_i.data = F.softmax(self.weight_i, dim=1)

        self.item_index = torch.zeros([self.num_item], dtype=torch.long)
        index = []
        for i in range(self.num_item):
            self.item_index[i] = i
            index.append(i)
        self.drop_percent = self.drop_rate
        self.single_percent = 1
        self.double_percent = 0

        drop_item = torch.tensor(
            np.random.choice(self.item_index, int(self.num_item * self.drop_percent), replace=False))
        drop_item_single = drop_item[:int(self.single_percent * len(drop_item))]

        self.dropv_node_idx_single = drop_item_single[:int(len(drop_item_single) * 1 / 3)]
        self.dropt_node_idx_single = drop_item_single[int(len(drop_item_single) * 2 / 3):]

        self.dropv_node_idx = self.dropv_node_idx_single
        self.dropt_node_idx = self.dropt_node_idx_single

        # mask_cnt: item下标， 记录每个item的度
        mask_cnt = torch.zeros(self.num_item, dtype=int).tolist()
        for edge in edge_index:
            mask_cnt[edge[1] - self.num_user] += 1

        # 构建保留与否向量
        mask_dropv = []
        mask_dropt = []
        for idx, num in enumerate(mask_cnt):
            temp_false = [False] * num
            temp_true = [True] * num
            mask_dropv.extend(temp_false) if idx in self.dropv_node_idx else mask_dropv.extend(temp_true)
            mask_dropt.extend(temp_false) if idx in self.dropt_node_idx else mask_dropt.extend(temp_true)

        edge_index = edge_index[np.lexsort(edge_index.T[1, None])]
        edge_index_dropv = edge_index[mask_dropv]
        edge_index_dropt = edge_index[mask_dropt]


        # edge_index_dropt， edge_index_dropv 为抽样之后的值
        self.edge_index_dropv = torch.tensor(edge_index_dropv).t().contiguous().to(self.device)
        self.edge_index_dropt = torch.tensor(edge_index_dropt).t().contiguous().to(self.device)

        self.edge_index_dropv = torch.cat((self.edge_index_dropv, self.edge_index_dropv[[1, 0]]), dim=1)
        self.edge_index_dropt = torch.cat((self.edge_index_dropt, self.edge_index_dropt[[1, 0]]), dim=1)
        # edge_index_dropt (114125, 2)
        # print("edge_index_dropt", edge_index_dropt.shape)
        self.MLP_user = nn.Linear(self.dim_latent * 2, self.dim_latent)

        if self.v_feat is not None:

            self.v_drop_ze = torch.zeros(len(self.dropv_node_idx), self.v_feat.size(1)).to(self.device)
            self.v_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                         num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=64,
                         device=self.device, features=self.v_feat)  # 256)
        if self.t_feat is not None:
            self.t_drop_ze = torch.zeros(len(self.dropt_node_idx), self.t_feat.size(1)).to(self.device)
            self.t_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                         num_layer=self.num_layer, has_id=has_id, dropout=self.drop_rate, dim_latent=64,
                         device=self.device, features=self.t_feat)


        self.user_graph = User_Graph_sample(num_user, 'add', self.dim_latent)

        self.result_embed = nn.Parameter(
            nn.init.xavier_normal_(torch.tensor(np.random.randn(num_user + num_item, dim_x * 2)))).to(self.device)
        
        self.num_blocks = config['res_block_num']  # 残差块的数量
        # 创建多层映射网络 - 为同质和多样性信息分别定义残差块
        self.v_homo_res_blocks = nn.ModuleList()  # 视觉模态同质信息的残差块
        self.v_diver_res_blocks = nn.ModuleList()  # 视觉模态多样性信息的残差块
        self.t_homo_res_blocks = nn.ModuleList()  # 文本模态同质信息的残差块
        self.t_diver_res_blocks = nn.ModuleList()  # 文本模态多样性信息的残差块

        for _ in range(self.num_blocks):
            # 视觉模态的同质信息残差块
            self.v_homo_res_blocks.append(
                FFN(hidden_size=self.dim_latent, inner_hidden_size=self.dim_latent*4, 
                    bias=True, activation_func=gelu)
            )
            # 视觉模态的多样性信息残差块
            self.v_diver_res_blocks.append(
                FFN(hidden_size=self.dim_latent, inner_hidden_size=self.dim_latent*4, 
                    bias=True, activation_func=gelu)
            )
            # 文本模态的同质信息残差块
            self.t_homo_res_blocks.append(
                FFN(hidden_size=self.dim_latent, inner_hidden_size=self.dim_latent*4, 
                    bias=True, activation_func=gelu)
            )
            # 文本模态的多样性信息残差块
            self.t_diver_res_blocks.append(
                FFN(hidden_size=self.dim_latent, inner_hidden_size=self.dim_latent*4, 
                    bias=True, activation_func=gelu)
            )

        # 添加初始的同质/多样性分离层
        self.v_homo_map = FFN(hidden_size=self.dim_latent, inner_hidden_size=self.dim_latent*4, 
                            bias=True, activation_func=gelu)
        self.v_diver_map = FFN(hidden_size=self.dim_latent, inner_hidden_size=self.dim_latent*4, 
                            bias=True, activation_func=gelu)

        self.t_homo_map = FFN(hidden_size=self.dim_latent, inner_hidden_size=self.dim_latent*4, 
                            bias=True, activation_func=gelu)
        self.t_diver_map = FFN(hidden_size=self.dim_latent, inner_hidden_size=self.dim_latent*4, 
                            bias=True, activation_func=gelu)

    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        # print("mm_embeddings.shape:", mm_embeddings.shape, "context_norm.shape", context_norm.shape)
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        # print("sim.shape:", sim.shape, "knn_ind.shape", knn_ind.shape)

        del sim

        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        # print("indices0.arange:", indices0.shape)

        indices0 = torch.unsqueeze(indices0, 1)
        # print("indices0.unsqueeze:", indices0.shape)

        indices0 = indices0.expand(-1, self.knn_k)
        # print("indices0.expand:", indices0.shape)

        # indices0.expand: torch.Size([7050, 5]), knn_ind.shape torch.Size([7050, 5])
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)

        # indices0.shape: torch.Size([7050, 5]) indices.shape torch.Size([2, 35250])
        # print("indices0.shape:", indices0.shape, "indices.shape", indices.shape)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)

    def compute_normalized_laplacian(self, indices, adj_size):
        # indices.shape torch.Size([2, 35250]), adj_size: torch.Size([7050, 5])
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pre_epoch_processing(self):
        self.epoch_user_graph, self.user_weight_matrix = self.topk_sample(self.k)
        self.user_weight_matrix = self.user_weight_matrix.to(self.device)

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        # ndarray([598918, 2]) for ml-imdb
        return np.column_stack((rows, cols))

    def diversity_constraint(self, diver_rep):
        """
        对多样性信息进行数值约束，防止过大/过小
        使用自适应梯度缩放技术，保持梯度流
        """
        # 1. 计算当前多样性信息的统计量
        rep_mean = diver_rep.mean()
        rep_std = diver_rep.std()
        
        # 2. 设置约束范围（可配置为超参数）
        clip_range = 2.0  # 标准差倍数范围
        
        # 3. 计算裁剪边界
        lower_bound = rep_mean - clip_range * rep_std
        upper_bound = rep_mean + clip_range * rep_std
        
        # 4. 使用torch.clamp进行裁剪
        clipped_rep = torch.clamp(diver_rep, min=lower_bound, max=upper_bound)
        
        # 5. 保持原始梯度（梯度重定向）
        return diver_rep + (clipped_rep - diver_rep).detach()

    def apply_resnet_blocks(self, rep, res_blocks):
        """应用多层残差块进行特征融合"""
        residual = rep
        for block in res_blocks:
            # 特征变换
            transformed = block(residual)
            
            # 残差连接
            residual = residual + transformed
        
        return residual

    def forward(self, interaction):
        user_nodes, pos_item_nodes, neg_item_nodes = interaction[0], interaction[1], interaction[2]
        pos_item_nodes += self.n_users
        neg_item_nodes += self.n_users

        if self.v_feat is not None:
            self.v_rep, self.v_preference = self.v_gcn(self.edge_index_dropv, self.edge_index, self.v_feat)
        if self.t_feat is not None:
            self.t_rep, self.t_preference = self.t_gcn(self.edge_index_dropt, self.edge_index, self.t_feat)

        v_rep = self.v_rep[self.num_user:]
        t_rep = self.t_rep[self.num_user:]

        # self.v_rep = torch.unsqueeze(self.v_rep, 2)
        # self.t_rep = torch.unsqueeze(self.t_rep, 2)
        # print("v_rep.shape.", self.v_rep[:self.num_user].shape, self.t_rep[:self.num_user].shape)
        # print("weight_u.shape.", self.weight_u.shape)

       
        # user_rep = torch.matmul(torch.cat((self.v_rep[:self.num_user], self.t_rep[:self.num_user]), dim=2), self.weight_u)
        # user_rep = torch.squeeze(user_rep)

        ############################################ multi-modal information aggregation
        """
        h = item_rep
        # print('device:', self.mm_adj.device, h.device)  # 输出：cpu

        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        h_u1 = self.user_graph(user_rep, self.epoch_user_graph, self.user_weight_matrix)
        user_rep = user_rep + h_u1
        item_rep = item_rep + h
        """
        # ****************** 同质信息的处理， 实验中可以放开这部分 ******************
        # h = (homogen_v_rep + homogen_t_rep) / 2
        # # print('device:', self.mm_adj.device, h.device)  # 输出：cpu
        t_h = t_rep
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, t_h)
        t_item_rep = t_h + h

        t_user_rep = self.t_rep[:self.num_user]
        h_u1 = self.user_graph(t_user_rep, self.epoch_user_graph, self.user_weight_matrix)
        t_user_rep = t_user_rep + h_u1


        v_h = v_rep
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, v_h)
        v_item_rep = v_h + h

        # user_matrix.shape torch.Size([19445, 1, 40]), u_features.shape. torch.Size([19445, 40, 64, 1]) 
        # ok: user_matrix: torch.Size([19445, 1, 40]) u_features.shape. torch.Size([19445, 40, 128]) 
        v_user_rep = self.v_rep[:self.num_user]
        h_u1 = self.user_graph(v_user_rep, self.epoch_user_graph, self.user_weight_matrix)
        v_user_rep = v_user_rep + h_u1

        t_user_rep = torch.unsqueeze(t_user_rep, 2)
        v_user_rep = torch.unsqueeze(v_user_rep, 2)
        user_rep = torch.matmul(torch.cat((t_user_rep, v_user_rep), dim=2), self.weight_u)
        user_rep = torch.squeeze(user_rep)
        # pdb.set_trace()
        # # print("user_rep", user_rep.shape, user_rep.dtype, item_rep.shape, item_rep.dtype)
        # self.result_embed = torch.cat((user_rep, item_rep), dim=0)
        # # self.result_embed = nn.Parameter(torch.cat((user_rep, item_rep), dim=0))
        # user_tensor = self.result_embed[user_nodes]
        # pos_item_tensor = self.result_embed[pos_item_nodes]
        # neg_item_tensor = self.result_embed[neg_item_nodes]
        # pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        # neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
        
            
        # # ****************** 多模态对齐（特征融合和分离）******************
        # # 1. 应用多层残差块进行特征融合
        # v_fused = self.apply_resnet_blocks(v_rep, self.v_res_blocks)
        # t_fused = self.apply_resnet_blocks(t_rep, self.t_res_blocks)

        # # 2. 在最后一层分离同质和多样性信息
        # v_homo = self.v_homo_map(v_fused)
        # v_diver = v_fused - v_homo
        # v_diver = self.v_diver_map(v_diver)
        # v_diver = self.diversity_constraint(v_diver)

        # t_homo = self.t_homo_map(t_fused)
        # t_diver = t_fused - t_homo
        # t_diver = self.t_diver_map(t_diver)
        # t_diver = self.diversity_constraint(t_diver)

        # # 3. 最终特征表示（残差连接）
        # v_rep = v_rep + v_homo + v_diver
        # t_rep = t_rep + t_homo + t_diver
        # ****************** 多模态对齐（特征融合和分离）******************
        # 1. 初始分离同质和多样性信息
        v_homo = self.v_homo_map(v_rep)
        v_diver = v_rep - v_homo
        v_diver = self.v_diver_map(v_diver)
        v_diver = self.diversity_constraint(v_diver)

        t_homo = self.t_homo_map(t_rep)
        t_diver = t_rep - t_homo
        t_diver = self.t_diver_map(t_diver)
        t_diver = self.diversity_constraint(t_diver)
        
        # 2. 对同质和多样性信息分别应用残差块
        # 应用多层残差块进行特征融合
        v_homo = self.apply_resnet_blocks(v_homo, self.v_homo_res_blocks)
        v_diver = self.apply_resnet_blocks(v_diver, self.v_diver_res_blocks)
        
        t_homo = self.apply_resnet_blocks(t_homo, self.t_homo_res_blocks)
        t_diver = self.apply_resnet_blocks(t_diver, self.t_diver_res_blocks)
        
        # 3. 最终特征表示（融合同质和多样性信息）
        v_rep = v_homo + v_diver + v_rep
        t_rep = t_homo + t_diver + t_rep
        # combined = torch.cat([v_rep, t_rep], dim=1)
        # gate_score = self.gate(combined)
        # item_rep = gate_score * v_rep + (1 - gate_score) * t_rep
        item_rep = self.v_weight * (v_rep) + self.t_weight * (t_rep)
        # item_rep = v_rep + t_rep
        # pdb.set_trace()
        # item_rep = torch.cat([v_rep,t_rep],dim=1)

        ###############TODO：下这一部分是之前说的做QKV，也就是Attention的部分###########
        self.result_embed = torch.cat((user_rep, item_rep), dim=0)

        user_tensor = self.result_embed[user_nodes]
        pos_item_tensor = self.result_embed[pos_item_nodes]
        neg_item_tensor = self.result_embed[neg_item_nodes]

        # diversity_v_embed_pos = torch.cat((user_rep, diversity_v_rep), dim=0)[pos_item_nodes]
        # diversity_t_embed_pos = torch.cat((user_rep, diversity_t_rep), dim=0)[pos_item_nodes]

        # diversity_v_embed_neg = torch.cat((user_rep, diversity_v_rep), dim=0)[neg_item_nodes]
        # diversity_t_embed_neg = torch.cat((user_rep, diversity_t_rep), dim=0)[neg_item_nodes]


        diversity_v_embed_pos = torch.cat((user_rep, v_item_rep), dim=0)[pos_item_nodes]
        diversity_t_embed_pos = torch.cat((user_rep, t_item_rep), dim=0)[pos_item_nodes]

        diversity_v_embed_neg = torch.cat((user_rep, v_item_rep), dim=0)[neg_item_nodes]
        diversity_t_embed_neg = torch.cat((user_rep, t_item_rep), dim=0)[neg_item_nodes]

        def QKV(user_tensor, k_list):
            k_values_tensor = torch.stack(k_list)
            # print("k_values_tensor:", k_values_tensor.shape)

            # 步骤1：计算相似度得分（原始注意力分数）
            sim_scores = torch.einsum('nd,knd->kn', user_tensor, k_values_tensor)  # 形状 [K, N]
            # 步骤2：沿K维度对分数做Softmax归一化
            weights = torch.softmax(sim_scores, dim=0)     # 形状 [K, N]
            # 步骤3：对k向量加权并沿K维度求和
            weighted_k = k_values_tensor * weights.unsqueeze(-1)         # 形状 [K, N, D]
            final_item_rep = torch.sum(weighted_k, dim=0)          # 形状 [N, D]
            return final_item_rep

        # k_list = [pos_item_tensor, diversity_v_embed_pos, diversity_t_embed_pos]
        # pos_item_rep = QKV(user_tensor, k_list)

        # k_list = [neg_item_tensor, diversity_v_embed_neg, diversity_t_embed_neg]
        # neg_item_rep = QKV(user_tensor, k_list)
        k_list = [pos_item_tensor, diversity_v_embed_pos, diversity_t_embed_pos]
        pos_item_rep = QKV(user_tensor, k_list)

        k_list = [neg_item_tensor, diversity_v_embed_neg, diversity_t_embed_neg]
        neg_item_rep = QKV(user_tensor, k_list)
        pos_scores = torch.sum(user_tensor * pos_item_rep, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_rep, dim=1)

        # pos_scores = torch.sum(F.cosine_similarity(user_tensor, pos_item_rep), dim=1)
        # neg_scores = torch.sum(F.cosine_similarity(user_tensor, neg_item_rep), dim=1)

        # return pos_scores, neg_scores, homogen_t_rep, homogen_v_rep
        return pos_scores, neg_scores, t_homo, v_homo, t_diver, v_diver

    def v_t_align_loss(self,v_rep,t_rep):
        def mmd_linear(t_rep, v_rep):
            """线性时间MMD近似"""
            mean_t = t_rep.mean(0)
            mean_v = v_rep.mean(0)
            mean_diff = (mean_t - mean_v).pow(2).sum()
            return mean_diff
        return mmd_linear(v_rep,t_rep)
    
    def v_t_diver_loss(self,v_rep,t_rep):
        # 这里是PAMD原始论文的做法
        dot_prod = torch.sum(torch.mul(v_rep, t_rep), dim=1)
        L_ort = torch.mean(dot_prod ** 2, dim=0)

        # 我突然想到这里也可以考虑同样的类似于MMD的方法，可以先取均值，再进行计算,如有必要,可以开放下面的部分:
        # # 计算两个模态的均值向量
        # mean_t = t_rep.mean(dim=0)  # [dim_latent]
        # mean_v = v_rep.mean(dim=0)  # [dim_latent]
        # mean_t = mean_t.squeeze()
        # mean_v = mean_v.squeeze()
        # # 计算内积的平方
        # dot_prod = torch.dot(mean_t, mean_v)  # 标量值
        # L_ort = dot_prod ** 2  # 内积的平方
        # # pdb.set_trace()
        return L_ort

    def calculate_loss(self, interaction):
        user = interaction[0]
        pos_scores, neg_scores, t_homo, v_homo, t_diver, v_diver = self.forward(interaction)
        # pos_scores, neg_scores = self.forward(interaction)
        loss_value = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))

        reg_embedding_loss_v = (self.v_preference[user] ** 2).mean() if self.v_preference is not None else 0.0
        reg_embedding_loss_t = (self.t_preference[user] ** 2).mean() if self.t_preference is not None else 0.0

        reg_loss = self.reg_weight * (reg_embedding_loss_v + reg_embedding_loss_t)

        reg_loss += self.reg_weight * (self.weight_u ** 2).mean()
        
        align_loss = self.v_t_align_loss(v_homo,t_homo) # 同质信息对齐

        diver_loss = self.v_t_diver_loss(v_diver,t_diver)

        return loss_value + reg_loss + align_loss + diver_loss


    def full_sort_predict(self, interaction):
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        temp_user_tensor = user_tensor[interaction[0], :]
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix

    def topk_sample(self, k):
        user_graph_index = []
        count_num = 0
        user_weight_matrix = torch.zeros(len(self.user_graph_dict), k)
        tasike = []
        for i in range(k):
            tasike.append(0)
        for i in range(len(self.user_graph_dict)):
            if len(self.user_graph_dict[i][0]) < k:
                count_num += 1
                if len(self.user_graph_dict[i][0]) == 0:
                    # pdb.set_trace()
                    user_graph_index.append(tasike)
                    continue
                user_graph_sample = self.user_graph_dict[i][0][:k]
                user_graph_weight = self.user_graph_dict[i][1][:k]
                while len(user_graph_sample) < k:
                    rand_index = np.random.randint(0, len(user_graph_sample))
                    user_graph_sample.append(user_graph_sample[rand_index])
                    user_graph_weight.append(user_graph_weight[rand_index])
                user_graph_index.append(user_graph_sample)

                if self.user_aggr_mode == 'softmax':
                    user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)  # softmax
                if self.user_aggr_mode == 'mean':
                    user_weight_matrix[i] = torch.ones(k) / k  # mean
                continue
            user_graph_sample = self.user_graph_dict[i][0][:k]
            user_graph_weight = self.user_graph_dict[i][1][:k]

            if self.user_aggr_mode == 'softmax':
                user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)  # softmax
            if self.user_aggr_mode == 'mean':
                user_weight_matrix[i] = torch.ones(k) / k  # mean
            user_graph_index.append(user_graph_sample)

        # pdb.set_trace()
        return user_graph_index, user_weight_matrix


class User_Graph_sample(torch.nn.Module):
    def __init__(self, num_user, aggr_mode, dim_latent):
        super(User_Graph_sample, self).__init__()
        self.num_user = num_user
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode

    def forward(self, features, user_graph, user_matrix):
        index = user_graph
        u_features = features[index]
        user_matrix = user_matrix.unsqueeze(1)
        # pdb.set_trace()
        # print("user_matrix.shape", user_matrix.shape, "u_features.shape.", u_features.shape,)

        u_pre = torch.matmul(user_matrix,u_features)

        # print("u_pre.shape.", u_pre.shape)
        u_pre = u_pre.squeeze()
        # print("u_pre.squeeze.shape.", u_pre.shape)
        return u_pre


class GCN(torch.nn.Module):
    def __init__(self, datasets, batch_size, num_user, num_item, dim_id, aggr_mode, num_layer, has_id, dropout,
                 dim_latent=None, device=None, features=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.num_layer = num_layer
        self.has_id = has_id
        self.dropout = dropout
        self.device = device

        if self.dim_latent:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
            self.MLP = nn.Linear(self.dim_feat, 4 * self.dim_latent)
            self.MLP_1 = nn.Linear(4 * self.dim_latent, self.dim_latent)
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self, edge_index_drop,edge_index,features):
        # features: item multimodal feature
        temp_features = self.MLP_1(F.leaky_relu(self.MLP(features))) if self.dim_latent else features
        x = torch.cat((self.preference, temp_features), dim=0).to(self.device)
        # x: user + item
        x = F.normalize(x).to(self.device)
        h = self.conv_embed_1(x, edge_index)  # equation 1
        h_1 = self.conv_embed_1(h, edge_index)
        x_hat = h + x + h_1
        return x_hat, self.preference


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index, size=None):
        # pdb.set_trace()
        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # print("base.gcn.forward.x.shape:", x.shape)
        # pdb.set_trace()
        # propagate: message() -> aggregate() -> update()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)

    def message(self, x_j, edge_index, size):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            # print("message.x_j.shape:", deg.shape, x_j.shape, norm.view(-1, 1).shape, edge_index.shape, size)
            return norm.view(-1, 1) * x_j
        # print("message.x_j.shape:", x_j.shape, edge_index.shape, size)
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)


class GEGLU(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.activation_fn = F.gelu

    def forward(self, x):
        # dim=-1 breaks in jit for pt<1.10
        x1, x2 = x.chunk(2, dim=(x.ndim - 1))
        return x1 * self.activation_fn(x2)



# @torch.jit.script
def gelu_impl(x):
    """OpenAI's gelu implementation."""
    return 0.5 * x * (1.0 + torch.tanh(0.7978845608028654 * x *
                                       (1.0 + 0.044715 * x * x)))

def gelu(x):
    return gelu_impl(x)

class FFN(torch.nn.Module):
    def __init__(self, hidden_size, inner_hidden_size=None,
                 bias=True, activation_func=gelu):
        super(FFN, self).__init__()
        self.hidden_size = hidden_size
        if inner_hidden_size is None:
            inner_hidden_size = 4 * hidden_size
        self.inner_hidden_size = inner_hidden_size
        self.layers = torch.nn.Sequential(
            torch.nn.Linear(self.hidden_size, self.inner_hidden_size, bias=bias),
            nn.GELU(),
            torch.nn.Linear(self.inner_hidden_size, self.hidden_size, bias=bias),
        )

    def forward(self, hidden_states):
        """
        hidden_states: [item_num,hidden_size]
        """
        output = self.layers(hidden_states)
        return output


class MMDLoss(nn.Module):
    '''
    计算源域数据和目标域数据的MMD距离
    Params:
    source: 源域数据（n * len(x))
    target: 目标域数据（m * len(y))
    kernel_mul:
    kernel_num: 取不同高斯核的数量
    fix_sigma: 不同高斯核的sigma值
    Return:
    loss: MMD loss
    '''
    def __init__(self, kernel_type='rbf', kernel_mul=2.0, kernel_num=5, fix_sigma=None, **kwargs):
        super(MMDLoss, self).__init__()
        self.kernel_num = kernel_num
        self.kernel_mul = kernel_mul
        self.fix_sigma = None
        self.kernel_type = kernel_type

    def guassian_kernel(self, source, target, kernel_mul, kernel_num, fix_sigma):
        n_samples = int(source.size()[0]) + int(target.size()[0])
        total = torch.cat([source, target], dim=0)
        total0 = total.unsqueeze(0).expand(
            int(total.size(0)), int(total.size(0)), int(total.size(1)))
        total1 = total.unsqueeze(1).expand(
            int(total.size(0)), int(total.size(0)), int(total.size(1)))
        L2_distance = ((total0-total1)**2).sum(2)
        if fix_sigma:
            bandwidth = fix_sigma
        else:
            bandwidth = torch.sum(L2_distance.data) / (n_samples**2-n_samples)
        bandwidth /= kernel_mul ** (kernel_num // 2)
        bandwidth_list = [bandwidth * (kernel_mul**i)
                          for i in range(kernel_num)]
        kernel_val = [torch.exp(-L2_distance / bandwidth_temp)
                      for bandwidth_temp in bandwidth_list]
        return sum(kernel_val)

    def linear_mmd2(self, f_of_X, f_of_Y):
        loss = 0.0
        delta = f_of_X.float().mean(0) - f_of_Y.float().mean(0)
        loss = delta.dot(delta.T)
        return loss

    def forward(self, source, target):
        if self.kernel_type == 'linear':
            return self.linear_mmd2(source, target)
        elif self.kernel_type == 'rbf':
            batch_size = int(source.size()[0])
            kernels = self.guassian_kernel(source, target, kernel_mul=self.kernel_mul, kernel_num=self.kernel_num, fix_sigma=self.fix_sigma)
            XX = torch.mean(kernels[:batch_size, :batch_size])
            YY = torch.mean(kernels[batch_size:, batch_size:])
            XY = torch.mean(kernels[:batch_size, batch_size:])
            YX = torch.mean(kernels[batch_size:, :batch_size])
            loss = torch.mean(XX + YY - XY - YX)
            return loss